const String countrySeedJson = '''
[
  { "id": 1, "name": "Afghanistan", "code": "AFG", "continentId": 3 },
  { "id": 2, "name": "Albania", "code": "ALB", "continentId": 1 },
  { "id": 3, "name": "Algeria", "code": "ALG", "continentId": 4 },
  { "id": 4, "name": "Andorra", "code": "AND", "continentId": 1 },
  { "id": 5, "name": "Angola", "code": "ANG", "continentId": 4 },
  { "id": 6, "name": "Antigua and Barbuda", "code": "ATG", "continentId": 5 },
  { "id": 7, "name": "Argentina", "code": "ARG", "continentId": 2 },
  { "id": 8, "name": "Armenia", "code": "ARM", "continentId": 1 },
  { "id": 9, "name": "Australia", "code": "AUS", "continentId": 3 },
  { "id": 10, "name": "Austria", "code": "AUT", "continentId": 1 },
  { "id": 11, "name": "Azerbaijan", "code": "AZE", "continentId": 3 },
  { "id": 12, "name": "Bahamas", "code": "BAH", "continentId": 5 },
  { "id": 13, "name": "Bahrain", "code": "BHR", "continentId": 3 },
  { "id": 14, "name": "Bangladesh", "code": "BAN", "continentId": 3 },
  { "id": 15, "name": "Barbados", "code": "BRB", "continentId": 5 },
  { "id": 16, "name": "Belarus", "code": "BLR", "continentId": 1 },
  { "id": 17, "name": "Belgium", "code": "BEL", "continentId": 1 },
  { "id": 18, "name": "Belize", "code": "BLZ", "continentId": 5 },
  { "id": 19, "name": "Benin", "code": "BEN", "continentId": 4 },
  { "id": 20, "name": "Bhutan", "code": "BHU", "continentId": 3 },
  { "id": 21, "name": "Bolivia", "code": "BOL", "continentId": 2 },
  { "id": 22, "name": "Bosnia and Herzegovina", "code": "BIH", "continentId": 1 },
  { "id": 23, "name": "Botswana", "code": "BOT", "continentId": 4 },
  { "id": 24, "name": "Brazil", "code": "BRA", "continentId": 2 },
  { "id": 25, "name": "Brunei Darussalam", "code": "BRU", "continentId": 3 },
  { "id": 26, "name": "Bulgaria", "code": "BUL", "continentId": 1 },
  { "id": 27, "name": "Burkina Faso", "code": "BFA", "continentId": 4 },
  { "id": 28, "name": "Burundi", "code": "BDI", "continentId": 4 },
  { "id": 29, "name": "Cabo Verde", "code": "CPV", "continentId": 4 },
  { "id": 30, "name": "Cambodia", "code": "CAM", "continentId": 3 },
  { "id": 31, "name": "Cameroon", "code": "CMR", "continentId": 4 },
  { "id": 32, "name": "Canada", "code": "CAN", "continentId": 5 },
  { "id": 33, "name": "Central African Republic", "code": "CTA", "continentId": 4 },
  { "id": 34, "name": "Chad", "code": "CHA", "continentId": 4 },
  { "id": 35, "name": "Chile", "code": "CHI", "continentId": 2 },
  { "id": 36, "name": "China PR", "code": "CHN", "continentId": 3 },
  { "id": 37, "name": "Chinese Taipei", "code": "TPE", "continentId": 3 },
  { "id": 38, "name": "Colombia", "code": "COL", "continentId": 2 },
  { "id": 39, "name": "Comoros", "code": "COM", "continentId": 4 },
  { "id": 40, "name": "Congo", "code": "CGO", "continentId": 4 },
  { "id": 41, "name": "DR Congo", "code": "COD", "continentId": 4 },
  { "id": 42, "name": "Costa Rica", "code": "CRC", "continentId": 5 },
  { "id": 43, "name": "Côte d'Ivoire", "code": "CIV", "continentId": 4 },
  { "id": 44, "name": "Croatia", "code": "CRO", "continentId": 1 },
  { "id": 45, "name": "Cuba", "code": "CUB", "continentId": 5 },
  { "id": 46, "name": "Curaçao", "code": "CUW", "continentId": 5 },
  { "id": 47, "name": "Cyprus", "code": "CYP", "continentId": 1 },
  { "id": 48, "name": "Czechia", "code": "CZE", "continentId": 1 },
  { "id": 49, "name": "Denmark", "code": "DEN", "continentId": 1 },
  { "id": 50, "name": "Djibouti", "code": "DJI", "continentId": 4 },
  { "id": 51, "name": "Dominica", "code": "DMA", "continentId": 5 },
  { "id": 52, "name": "Dominican Republic", "code": "DOM", "continentId": 5 },
  { "id": 53, "name": "Ecuador", "code": "ECU", "continentId": 2 },
  { "id": 54, "name": "Egypt", "code": "EGY", "continentId": 4 },
  { "id": 55, "name": "El Salvador", "code": "SLV", "continentId": 5 },
  { "id": 56, "name": "England", "code": "ENG", "continentId": 1 },
  { "id": 57, "name": "Equatorial Guinea", "code": "EQG", "continentId": 4 },
  { "id": 58, "name": "Eritrea", "code": "ERI", "continentId": 4 },
  { "id": 59, "name": "Estonia", "code": "EST", "continentId": 1 },
  { "id": 60, "name": "Eswatini", "code": "SWZ", "continentId": 4 },
  { "id": 61, "name": "Ethiopia", "code": "ETH", "continentId": 4 },
  { "id": 62, "name": "Faroe Islands", "code": "FRO", "continentId": 1 },
  { "id": 63, "name": "Fiji", "code": "FIJ", "continentId": 6 },
  { "id": 64, "name": "Finland", "code": "FIN", "continentId": 1 },
  { "id": 65, "name": "France", "code": "FRA", "continentId": 1 },
  { "id": 66, "name": "Gabon", "code": "GAB", "continentId": 4 },
  { "id": 67, "name": "Gambia", "code": "GAM", "continentId": 4 },
  { "id": 68, "name": "Georgia", "code": "GEO", "continentId": 1 },
  { "id": 69, "name": "Germany", "code": "GER", "continentId": 1 },
  { "id": 70, "name": "Ghana", "code": "GHA", "continentId": 4 },
  { "id": 71, "name": "Gibraltar", "code": "GIB", "continentId": 1 },
  { "id": 72, "name": "Greece", "code": "GRE", "continentId": 1 },
  { "id": 73, "name": "Grenada", "code": "GRN", "continentId": 5 },
  { "id": 74, "name": "Guam", "code": "GUM", "continentId": 6 },
  { "id": 75, "name": "Guatemala", "code": "GUA", "continentId": 5 },
  { "id": 76, "name": "Guinea", "code": "GUI", "continentId": 4 },
  { "id": 77, "name": "Guinea-Bissau", "code": "GNB", "continentId": 4 },
  { "id": 78, "name": "Guyana", "code": "GUY", "continentId": 2 },
  { "id": 79, "name": "Haiti", "code": "HAI", "continentId": 5 },
  { "id": 80, "name": "Honduras", "code": "HON", "continentId": 5 },
  { "id": 81, "name": "Hong Kong", "code": "HKG", "continentId": 3 },
  { "id": 82, "name": "Hungary", "code": "HUN", "continentId": 1 },
  { "id": 83, "name": "Iceland", "code": "ISL", "continentId": 1 },
  { "id": 84, "name": "India", "code": "IND", "continentId": 3 },
  { "id": 85, "name": "Indonesia", "code": "IDN", "continentId": 3 },
  { "id": 86, "name": "IR Iran", "code": "IRN", "continentId": 3 },
  { "id": 87, "name": "Iraq", "code": "IRQ", "continentId": 3 },
  { "id": 88, "name": "Ireland", "code": "IRL", "continentId": 1 },
  { "id": 89, "name": "Israel", "code": "ISR", "continentId": 1 },
  { "id": 90, "name": "Italy", "code": "ITA", "continentId": 1 },
  { "id": 91, "name": "Jamaica", "code": "JAM", "continentId": 5 },
  { "id": 92, "name": "Japan", "code": "JPN", "continentId": 3 },
  { "id": 93, "name": "Jordan", "code": "JOR", "continentId": 3 },
  { "id": 94, "name": "Kazakhstan", "code": "KAZ", "continentId": 1 },
  { "id": 95, "name": "Kenya", "code": "KEN", "continentId": 4 },
  {"id": 96, "name": "Korea DPR", "code": "PRK", "continentId": 3 },
  {"id": 97, "name": "Korea Republic", "code": "KOR", "continentId": 3 },
  { "id": 98, "name": "Kosovo", "code": "KOS", "continentId": 1 },
  { "id": 99, "name": "Kuwait", "code": "KUW", "continentId": 3 },
  { "id": 100, "name": "Kyrgyzstan", "code": "KGZ", "continentId": 3 },
  { "id": 101, "name": "Laos", "code": "LAO", "continentId": 3 },
  { "id": 102, "name": "Latvia", "code": "LVA", "continentId": 1 },
  { "id": 103, "name": "Lebanon", "code": "LBN", "continentId": 3 },
  { "id": 104, "name": "Lesotho", "code": "LES", "continentId": 4 },
  { "id": 105, "name": "Liberia", "code": "LBR", "continentId": 4 },
  { "id": 106, "name": "Libya", "code": "LBY", "continentId": 4 },
  { "id": 107, "name": "Liechtenstein", "code": "LIE", "continentId": 1 },
  { "id": 108, "name": "Lithuania", "code": "LTU", "continentId": 1 },
  { "id": 109, "name": "Luxembourg", "code": "LUX", "continentId": 1 },
  { "id": 110, "name": "Macao", "code": "MAC", "continentId": 3 },
  { "id": 111, "name": "Madagascar", "code": "MAD", "continentId": 4 },
  { "id": 112, "name": "Malawi", "code": "MWI", "continentId": 4 },
  { "id": 113, "name": "Malaysia", "code": "MAS", "continentId": 3 },
  { "id": 114, "name": "Maldives", "code": "MDV", "continentId": 3 },
  { "id": 115, "name": "Mali", "code": "MLI", "continentId": 4 },
  { "id": 116, "name": "Malta", "code": "MLT", "continentId": 1 },
  { "id": 117, "name": "Mauritania", "code": "MTN", "continentId": 4 },
  { "id": 118, "name": "Mauritius", "code": "MRI", "continentId": 4 },
  { "id": 119, "name": "Mexico", "code": "MEX", "continentId": 5 },
  { "id": 120, "name": "Moldova", "code": "MDA", "continentId": 1 },
  { "id": 121, "name": "Mongolia", "code": "MNG", "continentId": 3 },
  { "id": 122, "name": "Montenegro", "code": "MNE", "continentId": 1 },
  { "id": 123, "name": "Morocco", "code": "MAR", "continentId": 4 },
  { "id": 124, "name": "Mozambique", "code": "MOZ", "continentId": 4 },
  { "id": 125, "name": "Myanmar", "code": "MYA", "continentId": 3 },
  { "id": 126, "name": "Namibia", "code": "NAM", "continentId": 4 },
  { "id": 127, "name": "Nepal", "code": "NEP", "continentId": 3 },
  { "id": 128, "name": "Netherlands", "code": "NED", "continentId": 1 },
  { "id": 129, "name": "New Caledonia", "code": "NCL", "continentId": 6 },
  { "id": 130, "name": "New Zealand", "code": "NZL", "continentId": 6 },
  { "id": 131, "name": "Nicaragua", "code": "NCA", "continentId": 5 },
  { "id": 132, "name": "Niger", "code": "NIG", "continentId": 4 },
  { "id": 133, "name": "Nigeria", "code": "NGA", "continentId": 4 },
  { "id": 134, "name": "North Macedonia", "code": "MKD", "continentId": 1 },
  { "id": 135, "name": "Northern Ireland", "code": "NIR", "continentId": 1 },
  { "id": 136, "name": "Norway", "code": "NOR", "continentId": 1 },
  { "id": 137, "name": "Oman", "code": "OMA", "continentId": 3 },
  { "id": 138, "name": "Pakistan", "code": "PAK", "continentId": 3 },
  { "id": 139, "name": "Palestine", "code": "PLE", "continentId": 3 },
  { "id": 140, "name": "Panama", "code": "PAN", "continentId": 5 },
  { "id": 141, "name": "Papua New Guinea", "code": "PNG", "continentId": 6 },
  { "id": 142, "name": "Paraguay", "code": "PAR", "continentId": 2 },
  { "id": 143, "name": "Peru", "code": "PER", "continentId": 2 },
  { "id": 144, "name": "Philippines", "code": "PHI", "continentId": 3 },
  { "id": 145, "name": "Poland", "code": "POL", "continentId": 1 },
  { "id": 146, "name": "Portugal", "code": "POR", "continentId": 1 },
  { "id": 147, "name": "Qatar", "code": "QAT", "continentId": 3 },
  { "id": 148, "name": "Romania", "code": "ROU", "continentId": 1 },
  { "id": 149, "name": "Russia", "code": "RUS", "continentId": 1 },
  { "id": 150, "name": "Rwanda", "code": "RWA", "continentId": 4 },
  { "id": 151, "name": "Saint Kitts and Nevis", "code": "SKN", "continentId": 5 },
  { "id": 152, "name": "Saint Lucia", "code": "LCA", "continentId": 5 },
  { "id": 153, "name": "Saint Vincent and the Grenadines", "code": "VIN", "continentId": 5 },
  { "id": 154, "name": "Samoa", "code": "SAM", "continentId": 6 },
  { "id": 155, "name": "San Marino", "code": "SMR", "continentId": 1 },
  { "id": 156, "name": "São Tomé and Príncipe", "code": "STP", "continentId": 4 },
  { "id": 157, "name": "Saudi Arabia", "code": "KSA", "continentId": 3 },
  { "id": 158, "name": "Scotland", "code": "SCO", "continentId": 1 },
  { "id": 159, "name": "Senegal", "code": "SEN", "continentId": 4 },
  { "id": 160, "name": "Serbia", "code": "SRB", "continentId": 1 },
  { "id": 161, "name": "Seychelles", "code": "SEY", "continentId": 4 },
  { "id": 162, "name": "Sierra Leone", "code": "SLE", "continentId": 4 },
  { "id": 163, "name": "Singapore", "code": "SIN", "continentId": 3 },
  { "id": 164, "name": "Slovakia", "code": "SVK", "continentId": 1 },
  { "id": 165, "name": "Slovenia", "code": "SVN", "continentId": 1 },
  { "id": 166, "name": "Solomon Islands", "code": "SOL", "continentId": 6 },
  { "id": 167, "name": "Somalia", "code": "SOM", "continentId": 4 },
  { "id": 168, "name": "South Africa", "code": "RSA", "continentId": 4 },
  { "id": 169, "name": "South Sudan", "code": "SSD", "continentId": 4 },
  { "id": 170, "name": "Spain", "code": "ESP", "continentId": 1 },
  { "id": 171, "name": "Sri Lanka", "code": "SRI", "continentId": 3 },
  { "id": 172, "name": "Sudan", "code": "SDN", "continentId": 4 },
  { "id": 173, "name": "Suriname", "code": "SUR", "continentId": 2 },
  { "id": 174, "name": "Sweden", "code": "SWE", "continentId": 1 },
  { "id": 175, "name": "Switzerland", "code": "SUI", "continentId": 1 },
  { "id": 176, "name": "Syria", "code": "SYR", "continentId": 3 },
  { "id": 177, "name": "Tahiti", "code": "TAH", "continentId": 6 },
  { "id": 178, "name": "Tajikistan", "code": "TJK", "continentId": 3 },
  { "id": 179, "name": "Tanzania", "code": "TAN", "continentId": 4 },
  { "id": 180, "name": "Thailand", "code": "THA", "continentId": 3 },
  { "id": 181, "name": "Timor-Leste", "code": "TLS", "continentId": 3 },
  { "id": 182, "name": "Togo", "code": "TOG", "continentId": 4 },
  { "id": 183, "name": "Tonga", "code": "TGA", "continentId": 6 },
  { "id": 184, "name": "Trinidad and Tobago", "code": "TRI", "continentId": 5 },
  { "id": 185, "name": "Tunisia", "code": "TUN", "continentId": 4 },
  { "id": 186, "name": "Türkiye", "code": "TUR", "continentId": 1 },
  { "id": 187, "name": "Turkmenistan", "code": "TKM", "continentId": 3 },
  { "id": 188, "name": "Turks and Caicos Islands", "code": "TCA", "continentId": 5 },
  { "id": 189, "name": "Uganda", "code": "UGA", "continentId": 4 },
  { "id": 190, "name": "Ukraine", "code": "UKR", "continentId": 1 },
  { "id": 191, "name": "United Arab Emirates", "code": "UAE", "continentId": 3 },
  { "id": 192, "name": "United States", "code": "USA", "continentId": 5 },
  { "id": 193, "name": "Uruguay", "code": "URU", "continentId": 2 },
  { "id": 194, "name": "Uzbekistan", "code": "UZB", "continentId": 3 },
  { "id": 195, "name": "Vanuatu", "code": "VAN", "continentId": 6 },
  { "id": 196, "name": "Venezuela", "code": "VEN", "continentId": 2 },
  { "id": 197, "name": "Vietnam", "code": "VIE", "continentId": 3 },
  { "id": 198, "name": "British Virgin Islands", "code": "VGB", "continentId": 5 },
  { "id": 199, "name": "US Virgin Islands", "code": "VIR", "continentId": 5 },
  { "id": 200, "name": "Wales", "code": "WAL", "continentId": 1 },
  { "id": 201, "name": "Yemen", "code": "YEM", "continentId": 3 },
  { "id": 202, "name": "Zambia", "code": "ZAM", "continentId": 4 },
  { "id": 203, "name": "Zimbabwe", "code": "ZIM", "continentId": 4 },
  { "id": 204, "name": "Aruba", "code": "ARU", "continentId": 5 },
  { "id": 205, "name": "Anguilla", "code": "AIA", "continentId": 5 },
  { "id": 206, "name": "Bermuda", "code": "BER", "continentId": 5 },
  { "id": 207, "name": "Cayman Islands", "code": "CAY", "continentId": 5 },
  { "id": 208, "name": "Cook Islands", "code": "COK", "continentId": 6 },
  { "id": 209, "name": "Montserrat", "code": "MSR", "continentId": 5 },
  { "id": 210, "name": "American Samoa", "code": "ASA", "continentId": 6 },
  { "id": 211, "name": "Puerto Rico", "code": "PUR", "continentId": 5 }
]
''';
