name: ts1_core
description: Football match simulation core for Dart and Flutter apps.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  lints: ^6.0.0
  test: ^1.25.6
