import 'package:ts1_core/src/core/enums/player/role.dart';
import 'package:ts1_core/src/core/enums/player/duty.dart';
import 'package:ts1_core/src/core/enums/player/position.dart';

/// Maps each Role to the set of Positions where that role can be played.
final roleSupportedPositions = <Role, Set<Position>>{
  Role.shotStopper: {Position.goalKeeper},
  Role.sweeperKeeper: {Position.goalKeeper},
  Role.fullBack: {Position.rightBack, Position.leftBack},
  Role.wingBack: {Position.rightBack, Position.leftBack},
  Role.invertedFullBack: {Position.rightBack, Position.leftBack},
  Role.defensiveFullBack: {Position.rightBack, Position.leftBack},
  Role.centralDefender: {Position.centerBack},
  Role.stopper: {Position.centerBack},
  Role.ballPlayingDefender: {Position.centerBack},
  Role.wideBack: {Position.centerBack},
  Role.anchor: {Position.defensiveMidfielder},
  Role.ballWinningMidfielder: {
    Position.defensiveMidfielder,
    Position.centralMidfielder,
  },
  Role.regista: {Position.defensiveMidfielder, Position.centralMidfielder},
  Role.halfBack: {Position.defensiveMidfielder},
  Role.boxToBoxMidfielder: {Position.centralMidfielder},
  Role.mezzala: {Position.centralMidfielder},
  Role.carrilero: {Position.centralMidfielder},
  Role.boxCrasher: {Position.centralMidfielder},
  Role.shadowStriker: {Position.attackingMidfielder},
  Role.trequartista: {Position.attackingMidfielder},
  Role.enganche: {Position.attackingMidfielder},
  Role.halfWinger: {Position.attackingMidfielder},
  Role.winger: {Position.rightWinger, Position.leftWinger},
  Role.invertedWinger: {Position.rightWinger, Position.leftWinger},
  Role.widePlaymaker: {Position.rightWinger, Position.leftWinger},
  Role.defensiveWinger: {Position.rightWinger, Position.leftWinger},
  Role.targetMan: {Position.striker},
  Role.poacher: {Position.striker},
  Role.secondaryStriker: {Position.striker, Position.attackingMidfielder},
  Role.advancedForward: {Position.striker},
  Role.falseNine: {Position.striker},
};

/// Maps each Role to the set of Duties that role can perform.
final roleSupportedDuties = <Role, Set<Duty>>{
  Role.shotStopper: {Duty.defend, Duty.support},
  Role.sweeperKeeper: {Duty.support, Duty.attack},
  Role.fullBack: {Duty.defend, Duty.support, Duty.attack},
  Role.wingBack: {Duty.support, Duty.attack},
  Role.invertedFullBack: {Duty.defend, Duty.support},
  Role.defensiveFullBack: {Duty.defend, Duty.balanced},
  Role.centralDefender: {Duty.defend, Duty.support},
  Role.stopper: {Duty.defend, Duty.support},
  Role.ballPlayingDefender: {Duty.defend, Duty.support},
  Role.wideBack: {Duty.defend, Duty.support},
  Role.anchor: {Duty.defend, Duty.balanced},
  Role.ballWinningMidfielder: {Duty.defend, Duty.support},
  Role.regista: {Duty.defend, Duty.support},
  Role.halfBack: {Duty.defend, Duty.balanced},
  Role.boxToBoxMidfielder: {Duty.support, Duty.attack},
  Role.mezzala: {Duty.support, Duty.attack},
  Role.carrilero: {Duty.support, Duty.balanced},
  Role.boxCrasher: {Duty.attack, Duty.balanced},
  Role.shadowStriker: {Duty.attack, Duty.balanced},
  Role.trequartista: {Duty.support, Duty.attack},
  Role.enganche: {Duty.support, Duty.balanced},
  Role.halfWinger: {Duty.support, Duty.attack},
  Role.winger: {Duty.support, Duty.attack},
  Role.invertedWinger: {Duty.support, Duty.attack},
  Role.widePlaymaker: {Duty.support, Duty.attack},
  Role.defensiveWinger: {Duty.defend, Duty.support},
  Role.targetMan: {Duty.support, Duty.attack},
  Role.poacher: {Duty.attack, Duty.balanced},
  Role.secondaryStriker: {Duty.support, Duty.attack},
  Role.advancedForward: {Duty.attack, Duty.balanced},
  Role.falseNine: {Duty.support, Duty.attack},
};
