// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tactical_identity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TacticalIdentity _$TacticalIdentityFromJson(
  Map<String, dynamic> json,
) => _TacticalIdentity(
  id: (json['id'] as num).toInt(),
  riskTaking: (json['riskTaking'] as num).toDouble(),
  directnessBias: (json['directnessBias'] as num).toDouble(),
  verticalProgressionBias: (json['verticalProgressionBias'] as num).toDouble(),
  shortPassBias: (json['shortPassBias'] as num).toDouble(),
  widthBias: (json['widthBias'] as num).toDouble(),
  attackLeftBias: (json['attackLeftBias'] as num).toDouble(),
  attackCentralBias: (json['attackCentralBias'] as num).toDouble(),
  attackRightBias: (json['attackRightBias'] as num).toDouble(),
  throughBallBias: (json['throughBallBias'] as num).toDouble(),
  crossBias: (json['crossBias'] as num).toDouble(),
  cutbackBias: (json['cutbackBias'] as num).toDouble(),
  dribbleCreationBias: (json['dribbleCreationBias'] as num).toDouble(),
  longShotBias: (json['longShotBias'] as num).toDouble(),
  shotPatience: (json['shotPatience'] as num).toDouble(),
  defensiveLineHeight: (json['defensiveLineHeight'] as num).toDouble(),
  pressIntensityBias: (json['pressIntensityBias'] as num).toDouble(),
  pressTriggerRate: (json['pressTriggerRate'] as num).toDouble(),
  defensiveWidthBias: (json['defensiveWidthBias'] as num).toDouble(),
  compactnessBias: (json['compactnessBias'] as num).toDouble(),
  markingBias: (json['markingBias'] as num).toDouble(),
  tacklingAggressionBias: (json['tacklingAggressionBias'] as num).toDouble(),
  counterTriggerBias: (json['counterTriggerBias'] as num).toDouble(),
  counterpressBias: (json['counterpressBias'] as num).toDouble(),
  counterSpeedBias: (json['counterSpeedBias'] as num).toDouble(),
  setPieceAttackingBias: (json['setPieceAttackingBias'] as num).toDouble(),
  setPieceDefensiveBias: (json['setPieceDefensiveBias'] as num).toDouble(),
  possessionTilt: (json['possessionTilt'] as num).toDouble(),
  passWeightMult: (json['passWeightMult'] as num).toDouble(),
  turnoverWeightMult: (json['turnoverWeightMult'] as num).toDouble(),
  shotWeightMult: (json['shotWeightMult'] as num).toDouble(),
  shotConversionDelta: (json['shotConversionDelta'] as num).toDouble(),
);

Map<String, dynamic> _$TacticalIdentityToJson(_TacticalIdentity instance) =>
    <String, dynamic>{
      'id': instance.id,
      'riskTaking': instance.riskTaking,
      'directnessBias': instance.directnessBias,
      'verticalProgressionBias': instance.verticalProgressionBias,
      'shortPassBias': instance.shortPassBias,
      'widthBias': instance.widthBias,
      'attackLeftBias': instance.attackLeftBias,
      'attackCentralBias': instance.attackCentralBias,
      'attackRightBias': instance.attackRightBias,
      'throughBallBias': instance.throughBallBias,
      'crossBias': instance.crossBias,
      'cutbackBias': instance.cutbackBias,
      'dribbleCreationBias': instance.dribbleCreationBias,
      'longShotBias': instance.longShotBias,
      'shotPatience': instance.shotPatience,
      'defensiveLineHeight': instance.defensiveLineHeight,
      'pressIntensityBias': instance.pressIntensityBias,
      'pressTriggerRate': instance.pressTriggerRate,
      'defensiveWidthBias': instance.defensiveWidthBias,
      'compactnessBias': instance.compactnessBias,
      'markingBias': instance.markingBias,
      'tacklingAggressionBias': instance.tacklingAggressionBias,
      'counterTriggerBias': instance.counterTriggerBias,
      'counterpressBias': instance.counterpressBias,
      'counterSpeedBias': instance.counterSpeedBias,
      'setPieceAttackingBias': instance.setPieceAttackingBias,
      'setPieceDefensiveBias': instance.setPieceDefensiveBias,
      'possessionTilt': instance.possessionTilt,
      'passWeightMult': instance.passWeightMult,
      'turnoverWeightMult': instance.turnoverWeightMult,
      'shotWeightMult': instance.shotWeightMult,
      'shotConversionDelta': instance.shotConversionDelta,
    };
