const String countrySeedJson = '''
[
  { "id": 1, "name": "Afghanistan", "code": "AF", "continentId": 3 },
  { "id": 2, "name": "Albania", "code": "AL", "continentId": 1 },
  { "id": 3, "name": "Algeria", "code": "DZ", "continentId": 4 },
  { "id": 4, "name": "Andorra", "code": "AD", "continentId": 1 },
  { "id": 5, "name": "Angola", "code": "AO", "continentId": 4 },
  { "id": 6, "name": "Antigua and Barbuda", "code": "AG", "continentId": 5 },
  { "id": 7, "name": "Argentina", "code": "AR", "continentId": 2 },
  { "id": 8, "name": "Armenia", "code": "AM", "continentId": 3 },
  { "id": 9, "name": "Australia", "code": "AU", "continentId": 6 },
  { "id": 10, "name": "Austria", "code": "AT", "continentId": 1 },
  { "id": 11, "name": "Azerbaijan", "code": "AZ", "continentId": 3 },
  { "id": 12, "name": "Bahamas", "code": "BS", "continentId": 5 },
  { "id": 13, "name": "Bahrain", "code": "BH", "continentId": 3 },
  { "id": 14, "name": "Bangladesh", "code": "BD", "continentId": 3 },
  { "id": 15, "name": "Barbados", "code": "BB", "continentId": 5 },
  { "id": 16, "name": "Belarus", "code": "BY", "continentId": 1 },
  { "id": 17, "name": "Belgium", "code": "BE", "continentId": 1 },
  { "id": 18, "name": "Belize", "code": "BZ", "continentId": 5 },
  { "id": 19, "name": "Benin", "code": "BJ", "continentId": 4 },
  { "id": 20, "name": "Bhutan", "code": "BT", "continentId": 3 },
  { "id": 21, "name": "Bolivia (Plurinational State of)", "code": "BO", "continentId": 2 },
  { "id": 22, "name": "Bosnia and Herzegovina", "code": "BA", "continentId": 1 },
  { "id": 23, "name": "Botswana", "code": "BW", "continentId": 4 },
  { "id": 24, "name": "Brazil", "code": "BR", "continentId": 2 },
  { "id": 25, "name": "Brunei Darussalam", "code": "BN", "continentId": 3 },
  { "id": 26, "name": "Bulgaria", "code": "BG", "continentId": 1 },
  { "id": 27, "name": "Burkina Faso", "code": "BF", "continentId": 4 },
  { "id": 28, "name": "Burundi", "code": "BI", "continentId": 4 },
  { "id": 29, "name": "Cabo Verde", "code": "CV", "continentId": 4 },
  { "id": 30, "name": "Cambodia", "code": "KH", "continentId": 3 },
  { "id": 31, "name": "Cameroon", "code": "CM", "continentId": 4 },
  { "id": 32, "name": "Canada", "code": "CA", "continentId": 5 },
  { "id": 33, "name": "Central African Republic", "code": "CF", "continentId": 4 },
  { "id": 34, "name": "Chad", "code": "TD", "continentId": 4 },
  { "id": 35, "name": "Chile", "code": "CL", "continentId": 2 },
  { "id": 36, "name": "China", "code": "CN", "continentId": 3 },
  { "id": 37, "name": "Colombia", "code": "CO", "continentId": 2 },
  { "id": 38, "name": "Comoros", "code": "KM", "continentId": 4 },
  { "id": 39, "name": "Congo", "code": "CG", "continentId": 4 },
  { "id": 40, "name": "Congo, Democratic Republic of the", "code": "CD", "continentId": 4 },
  { "id": 41, "name": "Costa Rica", "code": "CR", "continentId": 5 },
  { "id": 42, "name": "Côte d'Ivoire", "code": "CI", "continentId": 4 },
  { "id": 43, "name": "Croatia", "code": "HR", "continentId": 1 },
  { "id": 44, "name": "Cuba", "code": "CU", "continentId": 5 },
  { "id": 45, "name": "Cyprus", "code": "CY", "continentId": 1 },
  { "id": 46, "name": "Czechia", "code": "CZ", "continentId": 1 },
  { "id": 47, "name": "Denmark", "code": "DK", "continentId": 1 },
  { "id": 48, "name": "Djibouti", "code": "DJ", "continentId": 4 },
  { "id": 49, "name": "Dominica", "code": "DM", "continentId": 5 },
  { "id": 50, "name": "Dominican Republic", "code": "DO", "continentId": 5 },
  { "id": 51, "name": "Ecuador", "code": "EC", "continentId": 2 },
  { "id": 52, "name": "Egypt", "code": "EG", "continentId": 4 },
  { "id": 53, "name": "El Salvador", "code": "SV", "continentId": 5 },
  { "id": 54, "name": "Equatorial Guinea", "code": "GQ", "continentId": 4 },
  { "id": 55, "name": "Eritrea", "code": "ER", "continentId": 4 },
  { "id": 56, "name": "Estonia", "code": "EE", "continentId": 1 },
  { "id": 57, "name": "Eswatini", "code": "SZ", "continentId": 4 },
  { "id": 58, "name": "Ethiopia", "code": "ET", "continentId": 4 },
  { "id": 59, "name": "Fiji", "code": "FJ", "continentId": 6 },
  { "id": 60, "name": "Finland", "code": "FI", "continentId": 1 },
  { "id": 61, "name": "France", "code": "FR", "continentId": 1 },
  { "id": 62, "name": "Gabon", "code": "GA", "continentId": 4 },
  { "id": 63, "name": "Gambia", "code": "GM", "continentId": 4 },
  { "id": 64, "name": "Georgia", "code": "GE", "continentId": 3 },
  { "id": 65, "name": "Germany", "code": "DE", "continentId": 1 },
  { "id": 66, "name": "Ghana", "code": "GH", "continentId": 4 },
  { "id": 67, "name": "Greece", "code": "GR", "continentId": 1 },
  { "id": 68, "name": "Grenada", "code": "GD", "continentId": 5 },
  { "id": 69, "name": "Guatemala", "code": "GT", "continentId": 5 },
  { "id": 70, "name": "Guinea", "code": "GN", "continentId": 4 },
  { "id": 71, "name": "Guinea-Bissau", "code": "GW", "continentId": 4 },
  { "id": 72, "name": "Guyana", "code": "GY", "continentId": 2 },
  { "id": 73, "name": "Haiti", "code": "HT", "continentId": 5 },
  { "id": 74, "name": "Honduras", "code": "HN", "continentId": 5 },
  { "id": 75, "name": "Hungary", "code": "HU", "continentId": 1 },
  { "id": 76, "name": "Iceland", "code": "IS", "continentId": 1 },
  { "id": 77, "name": "India", "code": "IN", "continentId": 3 },
  { "id": 78, "name": "Indonesia", "code": "ID", "continentId": 3 },
  { "id": 79, "name": "Iran (Islamic Republic of)", "code": "IR", "continentId": 3 },
  { "id": 80, "name": "Iraq", "code": "IQ", "continentId": 3 },
  { "id": 81, "name": "Ireland", "code": "IE", "continentId": 1 },
  { "id": 82, "name": "Israel", "code": "IL", "continentId": 3 },
  { "id": 83, "name": "Italy", "code": "IT", "continentId": 1 },
  { "id": 84, "name": "Jamaica", "code": "JM", "continentId": 5 },
  { "id": 85, "name": "Japan", "code": "JP", "continentId": 3 },
  { "id": 86, "name": "Jordan", "code": "JO", "continentId": 3 },
  { "id": 87, "name": "Kazakhstan", "code": "KZ", "continentId": 3 },
  { "id": 88, "name": "Kenya", "code": "KE", "continentId": 4 },
  { "id": 89, "name": "Kiribati", "code": "KI", "continentId": 6 },
  { "id": 90, "name": "Korea (Democratic People's Republic of)", "code": "KP", "continentId": 3 },
  { "id": 91, "name": "Korea, Republic of", "code": "KR", "continentId": 3 },
  { "id": 92, "name": "Kuwait", "code": "KW", "continentId": 3 },
  { "id": 93, "name": "Kyrgyzstan", "code": "KG", "continentId": 3 },
  { "id": 94, "name": "Lao People's Democratic Republic", "code": "LA", "continentId": 3 },
  { "id": 95, "name": "Latvia", "code": "LV", "continentId": 1 },
  { "id": 96, "name": "Lebanon", "code": "LB", "continentId": 3 },
  { "id": 97, "name": "Lesotho", "code": "LS", "continentId": 4 },
  { "id": 98, "name": "Liberia", "code": "LR", "continentId": 4 },
  { "id": 99, "name": "Libya", "code": "LY", "continentId": 4 },
  { "id": 100, "name": "Liechtenstein", "code": "LI", "continentId": 1 },
  { "id": 101, "name": "Lithuania", "code": "LT", "continentId": 1 },
  { "id": 102, "name": "Luxembourg", "code": "LU", "continentId": 1 },
  { "id": 103, "name": "Madagascar", "code": "MG", "continentId": 4 },
  { "id": 104, "name": "Malawi", "code": "MW", "continentId": 4 },
  { "id": 105, "name": "Malaysia", "code": "MY", "continentId": 3 },
  { "id": 106, "name": "Maldives", "code": "MV", "continentId": 3 },
  { "id": 107, "name": "Mali", "code": "ML", "continentId": 4 },
  { "id": 108, "name": "Malta", "code": "MT", "continentId": 1 },
  { "id": 109, "name": "Marshall Islands", "code": "MH", "continentId": 6 },
  { "id": 110, "name": "Mauritania", "code": "MR", "continentId": 4 },
  { "id": 111, "name": "Mauritius", "code": "MU", "continentId": 4 },
  { "id": 112, "name": "Mexico", "code": "MX", "continentId": 5 },
  { "id": 113, "name": "Micronesia (Federated States of)", "code": "FM", "continentId": 6 },
  { "id": 114, "name": "Moldova, Republic of", "code": "MD", "continentId": 1 },
  { "id": 115, "name": "Monaco", "code": "MC", "continentId": 1 },
  { "id": 116, "name": "Mongolia", "code": "MN", "continentId": 3 },
  { "id": 117, "name": "Montenegro", "code": "ME", "continentId": 1 },
  { "id": 118, "name": "Morocco", "code": "MA", "continentId": 4 },
  { "id": 119, "name": "Mozambique", "code": "MZ", "continentId": 4 },
  { "id": 120, "name": "Myanmar", "code": "MM", "continentId": 3 },
  { "id": 121, "name": "Namibia", "code": "NA", "continentId": 4 },
  { "id": 122, "name": "Nauru", "code": "NR", "continentId": 6 },
  { "id": 123, "name": "Nepal", "code": "NP", "continentId": 3 },
  { "id": 124, "name": "Netherlands", "code": "NL", "continentId": 1 },
  { "id": 125, "name": "New Zealand", "code": "NZ", "continentId": 6 },
  { "id": 126, "name": "Nicaragua", "code": "NI", "continentId": 5 },
  { "id": 127, "name": "Niger", "code": "NE", "continentId": 4 },
  { "id": 128, "name": "Nigeria", "code": "NG", "continentId": 4 },
  { "id": 129, "name": "North Macedonia", "code": "MK", "continentId": 1 },
  { "id": 130, "name": "Norway", "code": "NO", "continentId": 1 },
  { "id": 131, "name": "Oman", "code": "OM", "continentId": 3 },
  { "id": 132, "name": "Pakistan", "code": "PK", "continentId": 3 },
  { "id": 133, "name": "Palau", "code": "PW", "continentId": 6 },
  { "id": 134, "name": "Panama", "code": "PA", "continentId": 5 },
  { "id": 135, "name": "Papua New Guinea", "code": "PG", "continentId": 6 },
  { "id": 136, "name": "Paraguay", "code": "PY", "continentId": 2 },
  { "id": 137, "name": "Peru", "code": "PE", "continentId": 2 },
  { "id": 138, "name": "Philippines", "code": "PH", "continentId": 3 },
  { "id": 139, "name": "Poland", "code": "PL", "continentId": 1 },
  { "id": 140, "name": "Portugal", "code": "PT", "continentId": 1 },
  { "id": 141, "name": "Qatar", "code": "QA", "continentId": 3 },
  { "id": 142, "name": "Romania", "code": "RO", "continentId": 1 },
  { "id": 143, "name": "Russian Federation", "code": "RU", "continentId": 1 },
  { "id": 144, "name": "Rwanda", "code": "RW", "continentId": 4 },
  { "id": 145, "name": "Saint Kitts and Nevis", "code": "KN", "continentId": 5 },
  { "id": 146, "name": "Saint Lucia", "code": "LC", "continentId": 5 },
  { "id": 147, "name": "Saint Vincent and the Grenadines", "code": "VC", "continentId": 5 },
  { "id": 148, "name": "Samoa", "code": "WS", "continentId": 6 },
  { "id": 149, "name": "San Marino", "code": "SM", "continentId": 1 },
  { "id": 150, "name": "Sao Tome and Principe", "code": "ST", "continentId": 4 },
  { "id": 151, "name": "Saudi Arabia", "code": "SA", "continentId": 3 },
  { "id": 152, "name": "Senegal", "code": "SN", "continentId": 4 },
  { "id": 153, "name": "Serbia", "code": "RS", "continentId": 1 },
  { "id": 154, "name": "Seychelles", "code": "SC", "continentId": 4 },
  { "id": 155, "name": "Sierra Leone", "code": "SL", "continentId": 4 },
  { "id": 156, "name": "Singapore", "code": "SG", "continentId": 3 },
  { "id": 157, "name": "Slovakia", "code": "SK", "continentId": 1 },
  { "id": 158, "name": "Slovenia", "code": "SI", "continentId": 1 },
  { "id": 159, "name": "Solomon Islands", "code": "SB", "continentId": 6 },
  { "id": 160, "name": "Somalia", "code": "SO", "continentId": 4 },
  { "id": 161, "name": "South Africa", "code": "ZA", "continentId": 4 },
  { "id": 162, "name": "South Sudan", "code": "SS", "continentId": 4 },
  { "id": 163, "name": "Spain", "code": "ES", "continentId": 1 },
  { "id": 164, "name": "Sri Lanka", "code": "LK", "continentId": 3 },
  { "id": 165, "name": "Sudan", "code": "SD", "continentId": 4 },
  { "id": 166, "name": "Suriname", "code": "SR", "continentId": 2 },
  { "id": 167, "name": "Sweden", "code": "SE", "continentId": 1 },
  { "id": 168, "name": "Switzerland", "code": "CH", "continentId": 1 },
  { "id": 169, "name": "Syrian Arab Republic", "code": "SY", "continentId": 3 },
  { "id": 170, "name": "Tajikistan", "code": "TJ", "continentId": 3 },
  { "id": 171, "name": "Tanzania, United Republic of", "code": "TZ", "continentId": 4 },
  { "id": 172, "name": "Thailand", "code": "TH", "continentId": 3 },
  { "id": 173, "name": "Timor-Leste", "code": "TL", "continentId": 3 },
  { "id": 174, "name": "Togo", "code": "TG", "continentId": 4 },
  { "id": 175, "name": "Tonga", "code": "TO", "continentId": 6 },
  { "id": 176, "name": "Trinidad and Tobago", "code": "TT", "continentId": 5 },
  { "id": 177, "name": "Tunisia", "code": "TN", "continentId": 4 },
  { "id": 178, "name": "Türkiye", "code": "TR", "continentId": 1 },
  { "id": 179, "name": "Turkmenistan", "code": "TM", "continentId": 3 },
  { "id": 180, "name": "Tuvalu", "code": "TV", "continentId": 6 },
  { "id": 181, "name": "Uganda", "code": "UG", "continentId": 4 },
  { "id": 182, "name": "Ukraine", "code": "UA", "continentId": 1 },
  { "id": 183, "name": "United Arab Emirates", "code": "AE", "continentId": 3 },
  { "id": 184, "name": "United Kingdom of Great Britain and Northern Ireland", "code": "GB", "continentId": 1 },
  { "id": 185, "name": "United States of America", "code": "US", "continentId": 5 },
  { "id": 186, "name": "Uruguay", "code": "UY", "continentId": 2 },
  { "id": 187, "name": "Uzbekistan", "code": "UZ", "continentId": 3 },
  { "id": 188, "name": "Vanuatu", "code": "VU", "continentId": 6 },
  { "id": 189, "name": "Venezuela (Bolivarian Republic of)", "code": "VE", "continentId": 2 },
  { "id": 190, "name": "Viet Nam", "code": "VN", "continentId": 3 },
  { "id": 191, "name": "Yemen", "code": "YE", "continentId": 3 },
  { "id": 192, "name": "Zambia", "code": "ZM", "continentId": 4 },
  { "id": 193, "name": "Zimbabwe", "code": "ZW", "continentId": 4 },
  { "id": 194, "name": "Kosovo", "code": "XK", "continentId": 1 },
  { "id": 195, "name": "Palestine, State of", "code": "PS", "continentId": 3 },
  { "id": 196, "name": "Taiwan, Province of China", "code": "TW", "continentId": 3 },
  { "id": 197, "name": "Hong Kong", "code": "HK", "continentId": 3 },
  { "id": 198, "name": "Macao", "code": "MO", "continentId": 3 },
  { "id": 199, "name": "Puerto Rico", "code": "PR", "continentId": 5 },
  { "id": 200, "name": "Holy See", "code": "VA", "continentId": 1 }
]
''';
